#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
    update-rc.d varnish-hive remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi

# End automatically added section
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask varnish-hive.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge varnish-hive.service >/dev/null
		deb-systemd-helper unmask varnish-hive.service >/dev/null
	fi
	# uncomment this only if you want to delete the users
	# user_exists=$(id -u ${VARNISHHIVE_USER} > /dev/null 2>&1)
	# if [ $? ]; then
	#     deluser varnishhive
	# fi
fi
# End automatically added section
